# The basic descriptions of the graph processing platform.
platform.name = AvantGraph
platform.acronym = avantgraph
platform.version = 1.0
platform.link = https://git.avantgraph.io/ag/ldbc-graphalytics-platforms-avantgraph

# Source directory for AvantGraph
platform.avantgraph.source-directory =
platform.avantgraph.algorithms-directory =
